# Generated by Django 3.0.2 on 2020-01-10 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0003_auto_20200110_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoip',
            name='datecached',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
