# Generated by Django 3.0.2 on 2020-01-31 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArpBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArpMac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=60, unique=True)),
                ('ouiman', models.CharField(max_length=100, unique=True)),
                ('input_man', models.CharField(max_length=100, unique=True)),
                ('input_type', models.CharField(max_length=100, unique=True)),
                ('input_model', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArpStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArpReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotmmgmt.ArpBuffer')),
            ],
        ),
        migrations.AddField(
            model_name='arpbuffer',
            name='mac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotmmgmt.ArpMac'),
        ),
        migrations.AddField(
            model_name='arpbuffer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotmmgmt.ArpStatus'),
        ),
    ]
